
name: Build web

on:
  push:
    branches: [main]
    paths:
      - '.github/**'
      - 'ui/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '14'

      - run: |
          cd ui
          npm ci
          npm run lint
          npm run build --if-present
          npm run test --if-present
